name: News Updater
on:
  schedule:
    - cron: '0 * * * *'  # Runs at minute 0 of every hour
  workflow_dispatch:      # Allow manual runs

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install axios firebase-admin
      - run: node news-saver.js
        env:
          FIREBASE_CREDS: ${{ secrets.FIREBASE_CREDS }}
      - name: Upload creds
        run: echo "$FIREBASE_CREDS" > firebase-creds.json
