name: News Updater
on:
  schedule:
    - cron: '30 * * * *'
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install axios firebase-admin
      - name: Run news saver
        working-directory: ./server/services
        run: node news-saver.js
        env:
          FIREBASE_CREDS: ${{ secrets.FIREBASE_CREDS }}
