name: News Updater
on:
  schedule:
    - cron: '30 * * * *' # Runs at minute 30 of every hour (which corresponds to the start of each hour in IST)
  workflow_dispatch:

jobs:
  update-news:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install axios firebase-admin
      - name: Run news saver
        run: node news-saver.js
        env:
          FIREBASE_CREDS: ${{ secrets.FIREBASE_CREDS }} # Passes the secret as env variable
